[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
hdi = "=0.3.6"
hdk = "=0.2.6"
holo_hash = { version = "=0.2.6", features = ["encoding"] }
serde = "=1.0.166"
bincode = "1.3.3"
alloy-primitives = { version = "0.6.3", features = ["serde", "k256"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
bs58 = "0.5.0"
ethers-signers = "0.6.2"
holochain = { version = "0.2.6", default-features = false, features = [
  "test_utils",
] }
holochain_keystore = "0.2.6"
holochain_client = "0.4.8"
holochain_conductor_api = "0.2.6"
holochain_zome_types = "0.2.6"
rocket = "0.5.0"
rocket_okapi = { version = "0.8.0", features = ["swagger"] }

[workspace.dependencies.holoom_types]
path = "crates/holoom_types"

[workspace.dependencies.username_registry_validation]
path = "crates/username_registry_validation"

[workspace.dependencies.username_registry_integrity]
path = "crates/username_registry_integrity"

[workspace.dependencies.external_id_registry_validation]
path = "crates/external_id_registry_validation"

[workspace.dependencies.external_id_registry_integrity]
path = "crates/external_id_registry_integrity"

[workspace.dependencies.holoom_rocket_types]
path = "crates/holoom_rocket_types"

[workspace.dependencies.holoom_rocket_state]
path = "crates/holoom_rocket_state"

[workspace.dependencies.holoom_rocket_controllers]
path = "crates/holoom_rocket_controllers"
