[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
hdi = "=0.3"
hdk = "=0.2"
holo_hash = { version = "=0.2", features = ["encoding"] }
serde = "=1.0.166"
serde_json = "1.0.109"
bincode = "1.3.3"
alloy-primitives = { version = "0.6.3", features = ["serde", "k256"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
bs58 = "0.5.0"
ethers-signers = "0.6.2"
holochain = { version = "0.2", default-features = false, features = [
  "test_utils",
] }
holochain_keystore = "0.2"
holochain_client = "0.4"
holochain_conductor_api = "0.2"
holochain_zome_types = "0.2"
rocket = "0.5.0"
rocket_okapi = { version = "0.8.0", features = ["swagger"] }

[workspace.dependencies.holoom_types]
path = "crates/holoom_types"

[workspace.dependencies.jaq_wrapper]
path = "crates/jaq_wrapper"

[workspace.dependencies.username_registry_utils]
path = "crates/username_registry_utils"

[workspace.dependencies.username_registry_validation]
path = "crates/username_registry_validation"

[workspace.dependencies.username_registry_integrity]
path = "crates/username_registry_integrity"

[workspace.dependencies.username_registry_coordinator]
path = "crates/username_registry_coordinator"

[workspace.dependencies.signer_coordinator]
path = "crates/signer_coordinator"

[workspace.dependencies.holoom_rocket_types]
path = "crates/holoom_rocket_types"

[workspace.dependencies.holoom_rocket_state]
path = "crates/holoom_rocket_state"

[workspace.dependencies.holoom_rocket_controllers]
path = "crates/holoom_rocket_controllers"
