services:

  co2-sensor:
    build: ./co2-sensor
    volumes:
      - ../../packages/types/dist:/home/node/node_modules/@holoom/types/dist
      - ../../packages/authority/dist:/home/node/node_modules/@holoom/authority/dist
      - ../../workdir:/workdir