/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RecipeInstruction =
  | {
      type: "Constant";
      value: string;
    }
  | {
      type: "GetLatestDocWithIdentifier";
      var_name: string;
    }
  | {
      input_var_names: JqInstructionArgumentNames;
      program: string;
      type: "Jq";
    }
  | {
      type: "GetDocsListedByVar";
      var_name: string;
    }
  | {
      type: "GetCallerExternalId";
    }
  | {
      type: "GetCallerAgentPublicKey";
    };
export type JqInstructionArgumentNames =
  | {
      type: "Single";
      var_name: string;
    }
  | {
      type: "List";
      var_names: string[];
    };
