[package]
name = "ping_coordinator"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ping_coordinator"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
