[package]
name = "user_metadata_validation"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "user_metadata_validation"

[dependencies]
hdi = { workspace = true }
user_metadata_types = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
typeshare = { workspace = true }
