// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvmSigningOffer } from "./EvmSigningOffer";

export type CreateEvmSigningOfferPayload = {
  identifier: string;
  evm_signing_offer: EvmSigningOffer;
};
