import { ActionHash } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvmU256Item } from "./EvmU256Item";

export type EvmSigningOffer = { recipe_ah: ActionHash, u256_items: Array<EvmU256Item>, };
