// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JqExecutionInput } from "./JqExecutionInput";

export type JqExecution = {
  program: string;
  input: JqExecutionInput;
  output: string;
};
