// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JqInstructionArgumentNames } from "./JqInstructionArgumentNames";

export type RecipeInstruction =
  | { type: "Constant"; value: string }
  | { type: "GetLatestDocWithIdentifier"; var_name: string }
  | { type: "Jq"; input_var_names: JqInstructionArgumentNames; program: string }
  | { type: "GetDocsListedByVar"; var_name: string }
  | { type: "GetLatestCallerExternalId" }
  | { type: "GetCallerAgentPublicKey" };
