// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeArgument =
  | { type: "String"; value: string }
  | { type: "EvmAddress"; value: Uint8Array };
