import { Record, Signature } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignedEvmU256Array } from "./SignedEvmU256Array";

export type RemoteHoloomSignal =
  | { ExternalIdAttested: { request_id: string; record: Record } }
  | { ExternalIdRejected: { request_id: string; reason: string } }
  | {
      EvmSignatureProvided: {
        request_id: string;
        signed_u256_array: SignedEvmU256Array;
      };
    }
  | { EvmSignatureRequestRejected: { request_id: string; reason: string } };
