// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignedEvmU256Array = { raw: Uint8Array[], signature: [Uint8Array, Uint8Array, number], signer: Uint8Array, };
