import { ActionHash } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotInput = { "JqExecution": ActionHash } | { "OracleDocument": ActionHash } | { "RelationSnapshot": Array<string> };
