// Import prepended by scripts/add-imports-to-typeshare.ts
import { ActionHash, AgentPubKey, Record, Signature } from "@holochain/client";
import { EthAddress } from "./dependency-types";
/*
 Generated by typeshare 1.9.2
*/

/** A key-value pair, representing an item of a user's metadata */
export interface MetadataItem {
  name: string;
  value: string;
}

/** The input argument to `update_metadata_item`` */
export interface UpdateMetadataItemInput {
  /**
   * This has to be set to your own key. The only reason this field isn't
   * instead inferred is for the sake of enabling testing of the fail case.
   */
  agent_pubkey: AgentPubKey;
  /** The key for the particular metadata item */
  name: string;
  /** The value to assign to the key */
  value: string;
}

/** The input argument to `get_metadata_item_value`` */
export interface GetMetadataItemValueInput {
  /** The agent whose metadata you wish to query */
  agent_pubkey: AgentPubKey;
  /** The key for the particular metadata item */
  name: string;
}

/** Reasons for which a create `AgentMetadata` link action can fail validation. */
export enum CreateAgentMetadataLinkRejectionReason {
  /**
   * The base address is the agent pubkey of the user who is being annotated with metadata.
   * As a user can only author their own metadata, the base address has match their own pubkey.
   */
  BaseAddressMustBeOwner = "BaseAddressMustBeOwner",
  /** The link tag content doesn't match the expected key-value schema struct `MetadataItem`. */
  BadTagSerialization = "BadTagSerialization",
}

/** Reasons for which a delete `AgentMetadata` link action can fail validation. */
export enum DeleteAgentMetadataLinkRejectionReason {
  /**
   * The user attempting to delete the metadata item is not the owner and therefore doesn't
   * have permission.
   */
  DeleterIsNotOwner = "DeleterIsNotOwner",
}

export type ValidationRejectionDetail =
  | {
      type: "CreateAgentMetadataLinkRejectionReasons";
      reasons: CreateAgentMetadataLinkRejectionReason[];
    }
  | {
      type: "DeleteAgentMetadataLinkRejectionReasons";
      reasons: DeleteAgentMetadataLinkRejectionReason[];
    };
