// Import prepended by scripts/add-imports-to-typeshare.ts
import { ActionHash, AgentPubKey, Record, Signature } from "@holochain/client";
import { EthAddress } from "./dependency-types";
/*
 Generated by typeshare 1.9.2
*/

/** A key-value pair, representing an item of a user's metadata */
export interface MetadataItem {
  name: string;
  value: string;
}

/** The input argument to `update_metadata_item`` */
export interface UpdateMetadataItemInput {
  /**
   * This has to be set to your own key. The only reason this field isn't
   * instead inferred is for the sake of enabling testing of the fail case.
   */
  agent_pubkey: AgentPubKey;
  /** The key for the particular metadata item */
  name: string;
  /** The value to assign to the key */
  value: string;
}

/** The input argument to `get_metadata_item_value`` */
export interface GetMetadataItemValueInput {
  /** The agent whose metadata you wish to query */
  agent_pubkey: AgentPubKey;
  /** The key for the particular metadata item */
  name: string;
}
