import { AgentPubKey, ActionHash, Signature } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainWalletSignature } from "./ChainWalletSignature";

export type WalletAttestation = { agent: AgentPubKey, chain_wallet_signature: ChainWalletSignature, prev_action: ActionHash, };
