import { Signature } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChainWalletSignature =
  | {
      Evm: {
        evm_address: Uint8Array;
        evm_signature: [Uint8Array, Uint8Array, number];
      };
    }
  | { Solana: { solana_address: Uint8Array; solana_signature: number[] } };
