// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignedEvmSigningOffer } from "./SignedEvmSigningOffer";

export type CreateEvmSigningOfferPayload = {
  identifier: string;
  signed_offer: SignedEvmSigningOffer;
};
