import { ActionHash } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeArgument } from "./RecipeArgument";

export type ExecuteRecipePayload = {
  recipe_ah: ActionHash;
  arguments: Array<RecipeArgument>;
};
