import { AgentPubKey } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `get_attestation_for_external_id`
 */
export type GetAttestationForExternalIdPayload = {
  /**
   * The external ID for which to want a corresponding attestation
   */
  external_id: string;
  /**
   * The authorities whose attestations you respect.
   */
  trusted_authorities: AgentPubKey[];
};
