import { AgentPubKey } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `get_external_id_attestations_for_agent`
 */
export type GetExternalIdAttestationsForAgentPayload = {
  /**
   * The agent whose is the object of the attestations you wish to retrieve
   */
  agent_pubkey: AgentPubKey;
  /**
   * The authorities whose attestations you respect.
   */
  trusted_authorities: AgentPubKey[];
};
