import { AgentPubKey, Record, Signature } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignedEvmU256Array } from "./SignedEvmU256Array";

export type LocalHoloomSignal =
  | {
      type: "ExternalIdAttestationRequested";
      request_id: string;
      requestor_pubkey: AgentPubKey;
      code_verifier: string;
      code: string;
    }
  | { type: "ExternalIdAttested"; request_id: string; record: Record }
  | { type: "ExternalIdRejected"; request_id: string; reason: string }
  | {
      type: "EvmSignatureRequested";
      request_id: string;
      requestor_pubkey: AgentPubKey;
      u256_array: Uint8Array[];
    }
  | {
      type: "EvmSignatureProvided";
      request_id: string;
      signed_u256_array: SignedEvmU256Array;
    }
  | { type: "EvmSignatureRequestRejected"; request_id: string; reason: string };
