import { AgentPubKey } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeArgumentType } from "./RecipeArgumentType";
import type { RecipeInstruction } from "./RecipeInstruction";

export type Recipe = {
  trusted_authors: AgentPubKey[];
  arguments: Array<[string, RecipeArgumentType]>;
  instructions: Array<[string, RecipeInstruction]>;
};
