import { ActionHash } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeInstructionExecution =
  | "Constant"
  | { GetLatestDocWithIdentifier: { doc_ah: ActionHash } }
  | "Jq"
  | { GetDocsListedByVar: { doc_ahs: ActionHash[] } }
  | { GetLatestCallerExternalId: { attestation_ah: ActionHash } }
  | "GetCallerAgentPublicKey";
