import { AgentPubKey, Signature } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignedEvmU256Array } from "./SignedEvmU256Array";

export type ResolveEvmSignatureOverRecipeExecutionRequestPayload = {
  request_id: string;
  requestor: AgentPubKey;
  signed_u256_array: SignedEvmU256Array;
};
