import { AgentPubKey } from "@holochain/client";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The input to `sign_username_and_request_attestation`
 */
export type SignUsernameAndRequestAttestationInput = {
  /**
   * The username for which you want a corresponding attestation
   */
  username: string;
  /**
   * The authorities whose attestations you respect.
   */
  authority: AgentPubKey;
};
