[package]
name = "version_coordinator"
version = "0.0.1"
edition = "2021"
license = "CAL-1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "version_coordinator"

[dependencies]
hdk = { workspace = true }
